# Generated by Django 2.1.2 on 2018-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=10)),
                ('holder', models.CharField(blank=True, max_length=50)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('list', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.IntegerField(default=12)),
                ('back_color', models.CharField(blank=True, default='', max_length=7)),
                ('text_color', models.CharField(blank=True, default='', max_length=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('back_color', models.CharField(blank=True, default='', max_length=7)),
                ('text_color', models.CharField(blank=True, default='', max_length=7)),
                ('fields', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form_group',
            },
        ),
    ]
