# Generated by Django 2.1.2 on 2018-12-27 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('header_script', models.CharField(blank=True, max_length=4000, null=True)),
                ('body_script', models.CharField(blank=True, max_length=4000, null=True)),
                ('base_url', models.CharField(max_length=30)),
                ('view', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('is_hijack', models.BooleanField(default=False)),
                ('hijack_url', models.CharField(blank=True, max_length=300, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Company.Company')),
            ],
            options={
                'db_table': 'landing',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=3000, null=True)),
                ('is_banner', models.BooleanField(default=False)),
                ('banner_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('inner_db', models.BooleanField(default=False)),
                ('is_term', models.BooleanField(default=False)),
                ('image_term', models.BooleanField(default=False)),
                ('show_company', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Files.Image')),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Landing.Landing')),
            ],
            options={
                'db_table': 'layout',
            },
        ),
    ]
