# Generated by Django 2.1.5 on 2019-04-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Organization.Organization'),
        ),
    ]
